# 베이스 이미지: Confluent Kafka Connect (버전 6.2.0 사용)
FROM confluentinc/cp-kafka-connect:6.2.0

# Confluent Hub CLI를 이용하여 Aiven OpenSearch Sink Connector 설치
# RUN confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:latest
# RUN confluent-hub install --no-prompt io.aiven.kafka.connect.opensearch:3.3.0
# RUN confluent-hub install --no-prompt aiven/opensearch-connector-for-apache-kafka:3.3.0