version: '3.7'
services:
  # ZooKeeper: Kafka 클러스터 관리를 위한 코디네이터
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  # Kafka: 메시지 브로커
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # 컨테이너 내부 호스트네임 사용: "kafka" (또는 로컬 IP 활용)
      KAFKA_ADVERTISED_HOST_NAME: kafka
      # 컨테이너 시작 시 미리 토픽 생성
      # <토픽이름>:<파티션수>:<복제계수>
      KAFKA_CREATE_TOPICS: "ai_topic:1:1"
    depends_on:
      - zookeeper

  # FluentD: 로그 수집 및 Kafka 전송
  fluentd:
    build:
      context: .
      dockerfile: Dockerfile.fluentd
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes: # 로컬 디렉토리에서 마운트 시키는거임
      - ./fluentd/conf:/fluentd/etc  # FluentD 설정 파일
      - ./data:/fluentd/log          # AI JSON 파일 및 pos 파일 위치
    command: ["fluentd", "-c", "/fluentd/etc/fluent.conf", "-vv"]

  # Flink JobManager (스트림 처리 컨트롤러)
  flink-jobmanager:
    image: flink:1.15
    container_name: flink-jobmanager
    hostname: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    depends_on:
      - kafka

  # Flink TaskManager (실제 작업 처리 노드)
  flink-taskmanager:
    image: flink:1.15
    container_name: flink-taskmanager
    depends_on:
      - flink-jobmanager
    command: taskmanager

  # OpenSearch: 처리 결과 저장
  opensearch:
    image: opensearchproject/opensearch:2.3.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
      - "9600:9600"

  # Prometheus: 메트릭 수집
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Grafana: 대시보드 시각화
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
