version: '3.7'
services:
  # ZooKeeper: Kafka 클러스터 관리를 위한 코디네이터
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  # Kafka: 메시지 브로커
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "positive_topic:3:1,negative_topic:3:1,others_topic:3:1"
    depends_on:
      - zookeeper

  # FluentD: 로그 수집 및 Kafka 전송
  fluentd:
    build:
      context: .
      dockerfile: Dockerfile.fluentd
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./data:/fluentd/log
    command: ["fluentd", "-c", "/fluentd/etc/fluent.conf", "-vv"]

  # Flink JobManager
  flink-jobmanager:
    image: flink:1.15
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        jobmanager.rpc.port: 6123
        taskmanager.numberOfTaskSlots: 1
    networks:
      - flink-network
      - default

  # Flink TaskManager
  flink-taskmanager:
    image: flink:1.15
    container_name: flink-taskmanager
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 1
        taskmanager.memory.process.size: 1728m
    networks:
      - flink-network
      - default

  # OpenSearch: 처리 결과 저장
  opensearch:
    image: opensearchproject/opensearch:2.3.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
      - "9600:9600"

  # Prometheus: 메트릭 수집
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - opensearch-data:/usr/share/opensearch/data # 컨테이너 내부의 /usr/share/opensearch/data 디렉토리를 opensearch-data라는 이름의 Docker 볼륨에 마운트, 이를 통해 OpenSearch의 데이터가 컨테이너 외부의 볼륨에 저장되어 컨테이너가 삭제되어도 데이터가 유지
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    ports:
      - "9090:9090"

  # Grafana: 대시보드 시각화
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  flink-network:
    driver: bridge

# opensearch-data라는 이름의 Docker 볼륨을 정의합니다. 이 볼륨은 Docker에 의해 관리되며, 호스트 시스템의 특정 위치에 저장
volumes:
  opensearch-data: